import type { MetricKind } from "./insight-data";

const COMMON_METRICS: Record<string, string> = {
  activeUsers: "active users",
  activeSharePct: "active user share",
  advancedSharePct: "advanced adoption share",
  agentSharePct: "agent user share",
  aiCreditsPerActiveUser: "AI Credits per active user",
  aiCreditsUsed: "AI Credits used",
  avgDailyNetSpend: "average daily net spend",
  avgMedianMinutesToMerge: "average median time to merge",
  chatSharePct: "chat user share",
  cliSharePct: "command-line interface (CLI) user share",
  codeAccepted: "accepted code suggestions",
  codeAcceptedChangePct: "accepted code change",
  codeGenerated: "generated code suggestions",
  codeReviewSharePct: "code review user share",
  copilotAppliedSuggestions: "applied Copilot suggestions",
  copilotAuthoredPrs: "Copilot-authored pull requests",
  copilotAuthoredSharePct: "Copilot-authored pull request share",
  copilotReviewedPrs: "Copilot-reviewed pull requests",
  copilotReviewedSharePct: "Copilot-reviewed pull request share",
  costCenter: "cost center",
  creditsPerActiveMember: "AI Credits per active team member",
  creditsPerInteraction: "AI Credits per interaction",
  creditsUsed: "AI Credits used",
  evidenceCompletenessPct: "evidence completeness",
  fullyLoadedCostUsd: "fully loaded cost",
  idleSeatCostUsd: "idle seat cost",
  idleSeatRatePct: "idle seat rate",
  idleSeats: "idle seats",
  idleSeatsApprox: "approximate idle seats",
  interactions: "user-initiated interactions",
  interactionsChangePct: "interaction change",
  interactionsPerActiveUser: "interactions per active user",
  licenseAssignedDateCoveragePct: "license assignment date coverage",
  licensedUsers: "licensed users",
  linesOfCodeAdded: "lines of code added",
  netAmount: "net amount",
  netSpend: "net spend",
  netSpendChangePct: "net spend change",
  netSpendPerActiveUser: "net spend per active user",
  netValueUsd: "net value",
  organizationLogin: "organization",
  orgName: "organization",
  pendingCancellationCount: "pending cancellations",
  planCounts: "seats by plan",
  planType: "plan type",
  prCreated: "pull requests created",
  prCreatedChangePct: "pull request creation change",
  prMerged: "pull requests merged",
  prMergedChangePct: "pull request merge change",
  prReviewed: "pull requests reviewed",
  projected30DaySpend: "projected 30-day spend",
  projected90DaySpend: "projected 90-day spend",
  projectedAnnualSpend: "projected annual spend",
  roiRatio: "return on investment (ROI) ratio",
  sampleSize: "sample size",
  spendConcentration: "spend concentration",
  stickinessDauOverMau: "Daily Active Users over Monthly Active Users (DAU/MAU) stickiness",
  suggestionApplicationRatePct: "suggestion application rate",
  totalClassifiedUsers: "classified users",
  totalNetSpend: "total net spend",
  utilizationPct: "utilization",
  windowDays: "window length in days",
};

const KIND_METRICS: Partial<Record<MetricKind, Record<string, string>>> = {
  adoption: {
    earlyOrNoCohortSharePct: "early/no-cohort adoption share",
    agentFirstOrMultiAgentUsers: "agent-first or multi-agent users",
    dominantCohort: "dominant adoption cohort",
    primaryEnablementFocus: "primary enablement focus",
  },
  cost_license: {
    topModelSharePct: "top model spend share",
    top3ModelSharePct: "top three model spend share",
    licenseRisk: "license utilization risk",
    spendConcentrationRisk: "spend concentration risk",
    primaryOpportunity: "primary savings opportunity",
  },
  delivery: {
    deliveryTrend: "delivery trend",
    copilotContribution: "Copilot delivery contribution",
    primaryCaveat: "primary delivery caveat",
  },
  executive: {
    activityTrend: "activity trend",
    productivityTrend: "productivity trend",
    spendTrend: "spend trend",
    topRisk: "top enterprise risk",
    recommendedExecutiveDecision: "recommended executive decision",
  },
  roi_forecast: {
    estimatedHoursSaved: "estimated hours saved",
    estimatedValueUsd: "estimated value in US dollars",
    breakEvenHours: "break-even hours",
    forecastRisk: "forecast risk",
    roiJudgment: "return on investment (ROI) judgment",
  },
  team_scorecards: {
    activeMembers: "active team members",
    agentAdoptionSharePct: "agent adoption share",
    acceptanceRate: "acceptance rate",
    acceptanceVsMedianPoints: "acceptance compared with median",
    utilizationVsMedianPct: "utilization compared with median",
    creditsPerActiveMemberVsMedian: "AI Credits per active member compared with median",
  },
};

export function metricGlossaryFor(kind: MetricKind): Record<string, string> {
  return {
    ...COMMON_METRICS,
    ...(KIND_METRICS[kind] ?? {}),
  };
}
